Settings form qol
moinulmoin/chadnext pull request #51
Opened 2023-07-30 11:39 UTC by zahid47

addresses #49 

`shortBio` is marked as optional in the Prisma schema, so the initial value is `null` which doesn't match with the type `CurrentUser`. So I'm setting it as an empty string if it is null. Not sure if it is the best approach, but any advice is appreciated!

2023-07-30 16:18 UTC, moinulmoin commented
Thanks for the PR. I will check soon

2023-07-31 11:32 UTC, moinulmoin requested changes
you can just call optinal method at the end to make it optional. take a l

2023-07-31 11:32 UTC, moinulmoin commented on src/types/index.ts
> +    .or(z.literal("")),
you can just call optinal method at the end to make it optional. take a look here

https://zod.dev/?id=optionals

2023-07-31 11:37 UTC, moinulmoin commented on src/types/index.ts
> +    .or(z.literal("")),
```suggestion
  shortBio: z
    .string()
    .max(150, {
      message: "Short bio must be at most 150 characters.",
    })
    .min(10, {
      message: "Short bio must be at least 10 characters.",
    })
    .optional(),
```

2023-07-31 11:42 UTC, moinulmoin commented on src/app/dashboard/settings/settings-form.tsx
> +      shortBio: currentUser.shortBio || "",
```suggestion
      shortBio: currentUser.shortBio,
```

2023-07-31 11:48 UTC, moinulmoin requested changes

2023-07-31 11:48 UTC, moinulmoin commented on src/components/layout/image-upload-modal.tsx
> +              <div className="mt-10 flex">
```suggestion
              <div className="mt-10">
```

2023-07-31 11:50 UTC, moinulmoin commented on src/app/dashboard/settings/settings-form.tsx
> +        <div className="flex">
```suggestion
        <div>
```

2023-07-31 11:53 UTC, moinulmoin commented
All good. just need a few changes and then ready to merge. Thanks

2023-07-31 13:48 UTC, zahid47 commented
> you can just call optinal method at the end to make it optional. take a look here
> 
> https://zod.dev/?id=optionals

This was my first intuition as well. But it doesn't work if you type something in the short bio field and then remove it. Because then it becomes an empty string (""), but it won't let you update your profile with bio as an empty string as min length is 10 chars.

And the flex class in the other file is to fix the alignment with "cancel" button. During loading state the alignment gets messed up because of the loading icon

2023-07-31 14:40 UTC, moinulmoin commented
> And the flex class in the other file is to fix the alignment with "cancel" button. During loading state the alignment gets messed up and causes layout shift because of the loading icon

Hey, 

> > you can just call optinal method at the end to make it optional. take a look here
> > https://zod.dev/?id=optionals
> 
> This was my first intuition as well. But it doesn't work if you type something in the short bio field and then remove it. Because then it becomes an empty string (""), but it won't let you update your profile with bio as an empty string as min length is 10 chars.
> 
> And the flex class in the other file is to fix the alignment with "cancel" button. During loading state the alignment gets messed up and causes layout shift because of the loading icon

Hey, seems you are right, I removed the min and max and I noticed font flickering issue while checking the buttons layout shift. I added few adjustments. thanks.

2023-07-31 14:41 UTC, moinulmoin approved these changes

2023-07-31 14:43 UTC, merged